### PR TITLE
update the docs directory

### LINKED ISSUE #10: Update the docs directory files
### Proposed change

Update the docs directory files using the [JupyterHub python repo template](https://jupyterhub-python-repo-template.readthedocs.io/en/latest/docs.html#the-recommended-docs-directory-structure) as a reference

### (Optional): Suggest a solution

- [x] Add project logos
- [x] Update the conf.py file
- [x] Create a requirements.txt file
- [x] Update changelog.md file
- [x] Update the makefile
- [x] Update index.md
- [x] Update make.bat

### PR DESCRIPTION
**Pull request by Sheila-nk**
* added the requirements.txt file
* added the jupyterhub documentation logo
* added the conf.py file
* generated changelog.md file
* updated index.md
* updated makefile
* update make.bat

Closes #10

### CODE REVIEW

**Review by GeorgianaElena — COMMENTED** [review]
Thanks @Sheila-nk! Is this ready for review or is still a work in progress? 

Btw, I've imported the project on readthedocs and you can check out the build status of the docs at https://readthedocs.org/projects/jupyterhub-pytest-plugin/builds/

**Comment by Sheila-nk** [comment]
> Thanks @Sheila-nk! Is this ready for review or is still a work in progress?
> 
> Btw, I've imported the project on readthedocs and you can check out the build status of the docs at https://readthedocs.org/projects/jupyterhub-pytest-plugin/builds/

Hey @GeorgianaElena 
No, this is still a work in progress, it is not ready for review yet. I am updating the files using the repo template as a reference and modifying them for this project.

And being able to check the build status is really cool. Hopefully, the build will be successful when this PR is merged.

**Comment by Sheila-nk** [comment]
Hey @GeorgianaElena 
I have finished updating the doc files. I have run `make html` locally and the build was successful but I will need to improve the documentation as we go along.

**Review by GeorgianaElena — APPROVED** [review]
Awesome! Thansks @Sheila-nk!

**Comment by GeorgianaElena** [comment]
Yuhuuuu 🎉 🎉 The project has a docs page now https://jupyterhub-pytest-plugin.readthedocs.io/en/latest/ 🚀

**Comment by Sheila-nk** [comment]
> Yuhuuuu 🎉 🎉 The project has a docs page now https://jupyterhub-pytest-plugin.readthedocs.io/en/latest/ 🚀

Yeyy!! 🥳 🥳  I am sooo glad!
Thank you for your review!

**Pull request merged**
